version: '3'
services:
  app:
    build: .
    ports:
      - 5500:5500
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=someverysecurepassword
      - DB_NAME=wkldlabs
      - JWT_SECRET=nOtsOseCRethUh
      - JWT_REFRESH_EXPIRATION=7d
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=someverysecurepassword
      - MYSQL_DATABASE=wkldlabs